baseURL = 'https://bvkatwijk.github.io/'
languageCode = 'en-us'
title = 'Boris van Katwijk'
theme = 'ananke'

[params.ananke.social.follow]
new_window_icon = false
networks = [
    "twitter",
    "github",
  "linkedin"
]

[[params.ananke.social.twitter]]
username = "boris_katwijk"
label = "Boris van Katwijk Twitter"
rel = "me"

[[params.ananke.social.github]]
username = "bvkatwijk"
label = "Boris van Katwijk GitHub"
color = "#ff6800"

[[params.ananke.social.linkedin]]
username = "bvankatwijk"
label = "Boris van Katwijk LinkedIn"
color = "#0072b1"
rel = "me"

[markup.goldmark.renderer]
unsafe= true