baseURL = 'https://bvkatwijk.github.io/'
languageCode = 'en-us'
title = 'Boris van Katwijk'
theme = 'ananke'

[[ananke.social.twitter]]
username = "theNewDynamic"
profilelink = "https://twitter.com/theNewDynamic" #

[ananke.social.follow]
new_window_icon = false
networks = [
  "linkedin"
]

[ananke.social.github]
name = "github"
url = "https://github.com/bvkatwijk"
label = "Boris van Katwijk GitHub"
color = "#ff6800"


[ananke.social.linkedin]
username = "bvankatwijk"
label = "Boris van Katwijk LinkedIn"
color = "#0072b1"

[markup.goldmark.renderer]
unsafe= true