baseURL = 'https://bvkatwijk.github.io/'
languageCode = 'en-us'
title = 'Boris van Katwijk'
theme = 'ananke'

[ananke.social.follow]
new_window_icon = false
networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

[[ananke.social.twitter]]
username = "theNewDynamic"
profilelink = "https://twitter.com/theNewDynamic"

[[params.ananke.social.twitter]]
username = "boris_katwijk"
label = "Boris van Katwijk Twitter"

[[params.ananke.social.github]]
username = "bvkatwijk"
label = "Boris van Katwijk GitHub"
color = "#ff6800"

[[params.ananke.social.linkedin]]
username = "bvankatwijk"
label = "Boris van Katwijk LinkedIn"
color = "#0072b1"

[markup.goldmark.renderer]
unsafe= true