baseURL = 'https://bvkatwijk.github.io/'
languageCode = 'en-us'
title = 'Boris van Katwijk'
theme = 'ananke'

[params.ananke.social.follow]
new_window_icon = false
networks = [
    "github",
  "linkedin",
  "stackoverflow"
]

[params.ananke.social.share]
icons = true
sharetext = true
networks = [
  "email",
  "linkedin"
]

[params.ananke.social.github]
username = "bvkatwijk"

[params.ananke.social.linkedin]
username = "bvankatwijk"

[params.ananke.social.stackoverflow]
username = "5722607"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
identifier = "cv"
pre = "" # pre is inserted before the translation (icons, image, etc)
name = "CV"
url = "/cv"
weight = 30