baseURL = 'https://bvkatwijk.github.io/'
languageCode = 'en-us'
title = 'Boris van Katwijk'
theme = 'ananke'

[params.ananke.social.follow]
new_window_icon = false
networks = [
    "twitter",
    "github",
  "linkedin",
  "stackoverflow"
]

[params.ananke.social.share]
icons = true
sharetext = true
networks = [
  "email",
  "twitter",
  "linkedin"
]

[params.ananke.social.twitter]
username = "boris_katwijk"

[params.ananke.social.github]
username = "bvkatwijk"

[params.ananke.social.linkedin]
username = "bvankatwijk"

[params.ananke.social.stackoverflow]
username = "5722607"

[markup.goldmark.renderer]
unsafe= true